#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: Daniel Thaagaard Andreasen

# Short bio or description (displayed in the header)
description: PhD in astronomy at Porto, Portugal

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: img/me.jpg

#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
  email: daniel.andreasen@astro.up.pt
  facebook: daniel.t.andreasen
  github: DanielAndreasen
  rss: cool
  stackoverflow: users/1340702/daniel-thaagaard-andreasen

# Your disqus shortname, entering this will enable commenting on posts
disqus: Daniel

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: DanielAndreasen.github.io

# Use 10 post maximum on home page.
paginate: 2

#
# !! You don't need to change any of the configuration flags below !!
#

markdown: rdiscount
permalink: pretty
highlighter: pygments

# The release of Jekyll Now that you're using
# version: v1.0.0

# Set the Sass partials directory, as we're using @imports
sass:
  # sass_dir: _scss
  # style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
# gems:
  # - jemoji # Emoji please!
  # - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem

# Exclude these files from your production _site
# exclude:
    # - Gemfile
    # - Gemfile.lock
    # - LICENSE
    # - README.md
